# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/hltekdi/setup-makefiles.sh
PRODUCT_COPY_FILES := \
    vendor/samsung/hltekdi/proprietary/vendor/lib/libtime_genoff.so:obj/lib/libtime_genoff.so

PRODUCT_COPY_FILES += \
	vendor/samsung/hltekdi/proprietary/lib/libsensirion_h_12.so:system/lib/libsensirion_h_12.so \
	vendor/samsung/hltekdi/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
	vendor/samsung/hltekdi/proprietary/lib/libril.so:system/lib/libril.so \
	vendor/samsung/hltekdi/proprietary/lib/hw/sensors.msm8974.so:system/lib/hw/sensors.msm8974.so

PRODUCT_COPY_FILES += \
	vendor/samsung/hltekdi/proprietary/app/FeliCaLock.apk:system/app/FeliCaLock.apk \
	vendor/samsung/hltekdi/proprietary/app/FeliCaRemoteLock.apk:system/app/FeliCaRemoteLock.apk \
	vendor/samsung/hltekdi/proprietary/app/FeliCaTest.apk:system/app/FeliCaTest.apk \
	vendor/samsung/hltekdi/proprietary/app/MobileFeliCaClient.apk:system/app/MobileFeliCaClient.apk \
	vendor/samsung/hltekdi/proprietary/app/MobileFeliCaMenuApp.apk:system/app/MobileFeliCaMenuApp.apk \
	vendor/samsung/hltekdi/proprietary/app/MobileFeliCaSettingApp.apk:system/app/MobileFeliCaSettingApp.apk \
	vendor/samsung/hltekdi/proprietary/app/MobileFeliCaWebPluginBoot.apk:system/app/MobileFeliCaWebPluginBoot.apk \
	vendor/samsung/hltekdi/proprietary/app/FdtpApplication.apk:system/app/FdtpApplication.apk \
	vendor/samsung/hltekdi/proprietary/app/FdtpMfcAccess.apk:system/app/FdtpMfcAccess.apk \
	vendor/samsung/hltekdi/proprietary/lib/libcordon.so:system/lib/libcordon.so \
	vendor/samsung/hltekdi/proprietary/etc/felica/No_ticket.png:system/etc/felica/No_ticket.png \
	vendor/samsung/hltekdi/proprietary/etc/felica/air.png:system/etc/felica/air.png \
	vendor/samsung/hltekdi/proprietary/etc/felica/bookmark.cfg:system/etc/felica/bookmark.cfg \
	vendor/samsung/hltekdi/proprietary/etc/felica/common.cfg:system/etc/felica/common.cfg \
	vendor/samsung/hltekdi/proprietary/etc/felica/id.png:system/etc/felica/id.png \
	vendor/samsung/hltekdi/proprietary/etc/felica/mfc_falp.cfg:system/etc/felica/mfc_falp.cfg \
	vendor/samsung/hltekdi/proprietary/etc/felica/mfc_push.cfg:system/etc/felica/mfc_push.cfg \
	vendor/samsung/hltekdi/proprietary/etc/felica/mfm.cfg:system/etc/felica/mfm.cfg \
	vendor/samsung/hltekdi/proprietary/etc/felica/mfs.cfg:system/etc/felica/mfs.cfg \
	vendor/samsung/hltekdi/proprietary/etc/felica/money.png:system/etc/felica/money.png \
	vendor/samsung/hltekdi/proprietary/etc/felica/portal_icon.png:system/etc/felica/portal_icon.png \
	vendor/samsung/hltekdi/proprietary/etc/felica/toku.png:system/etc/felica/toku.png \
	vendor/samsung/hltekdi/proprietary/etc/felica/train.png:system/etc/felica/train.png
