# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/hltekdi/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/hltekdi/proprietary/etc/Bluetooth_cal.acdb:system/etc/Bluetooth_cal.acdb \
    vendor/samsung/hltekdi/proprietary/etc/Global_cal.acdb:system/etc/Global_cal.acdb \
    vendor/samsung/hltekdi/proprietary/etc/Handset_cal.acdb:system/etc/Handset_cal.acdb \
    vendor/samsung/hltekdi/proprietary/etc/Hdmi_cal.acdb:system/etc/Hdmi_cal.acdb \
    vendor/samsung/hltekdi/proprietary/etc/Headset_cal.acdb:system/etc/Headset_cal.acdb \
    vendor/samsung/hltekdi/proprietary/etc/Speaker_cal.acdb:system/etc/Speaker_cal.acdb \
    vendor/samsung/hltekdi/proprietary/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
    vendor/samsung/hltekdi/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/hltekdi/proprietary/bin/efsks:system/bin/efsks \
    vendor/samsung/hltekdi/proprietary/bin/qcks:system/bin/qcks \
    vendor/samsung/hltekdi/proprietary/lib/hw/sensors.msm8974.so:system/lib/hw/sensors.msm8974.so \
    vendor/samsung/hltekdi/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/hltekdi/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/hltekdi/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/hltekdi/proprietary/lib/libsensirion_h_12.so:system/lib/libsensirion_h_12.so \
    vendor/samsung/hltekdi/proprietary/vendor/firmware/bcm4335_V0105.0486.hcd:system/vendor/firmware/bcm4335_V0105.0486.hcd

# SONY NFC
PRODUCT_COPY_FILES += \
	vendor/samsung/hltekdi/proprietary/snfc/etc/snfc/auto_polling.cfg:system/etc/snfc/auto_polling.cfg \
	vendor/samsung/hltekdi/proprietary/snfc/etc/snfc/rf.cfg:system/etc/snfc/rf.cfg \
	vendor/samsung/hltekdi/proprietary/snfc/lib/libnfc_sony.so:system/lib/libnfc_sony.so \
	vendor/samsung/hltekdi/proprietary/snfc/lib/libnfc_sony_jni.so:system/lib/libnfc_sony_jni.so \
	vendor/samsung/hltekdi/proprietary/snfc/lib/libnfc_sony_ndef.so:system/lib/libnfc_sony_ndef.so \
	vendor/samsung/hltekdi/proprietary/app/MobileFeliCaClient.apk:system/app/MobileFeliCaClient/MobileFeliCaClient.apk \
	vendor/samsung/hltekdi/proprietary/app/MobileFeliCaMenuApp.apk:system/app/MobileFeliCaMenuApp/MobileFeliCaMenuApp.apk \
	vendor/samsung/hltekdi/proprietary/app/MobileFeliCaSettingApp.apk:system/app/MobileFeliCaSettingApp/MobileFeliCaSettingApp.apk \
	vendor/samsung/hltekdi/proprietary/app/MobileFeliCaWebPluginBoot.apk:system/app/MobileFeliCaWebPluginBoot/MobileFeliCaWebPluginBoot.apk \
	vendor/samsung/hltekdi/proprietary/bin/mfdp:system/bin/mfdp \
	vendor/samsung/hltekdi/proprietary/bin/mfsc:system/bin/mfsc \
	vendor/samsung/hltekdi/proprietary/etc/felica/common.cfg:system/etc/felica/common.cfg \
	vendor/samsung/hltekdi/proprietary/etc/felica/mfc_falp.cfg:system/etc/felica/mfc_falp.cfg \
	vendor/samsung/hltekdi/proprietary/etc/felica/mfc_push.cfg:system/etc/felica/mfc_push.cfg \
	vendor/samsung/hltekdi/proprietary/etc/felica/mfm.cfg:system/etc/felica/mfm.cfg \
	vendor/samsung/hltekdi/proprietary/etc/felica/mfs.cfg:system/etc/felica/mfs.cfg
