# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/hltedcm/setup-makefiles.sh
PRODUCT_COPY_FILES := \
    vendor/samsung/hltedcm/proprietary/vendor/lib/libtime_genoff.so:obj/lib/libtime_genoff.so

PRODUCT_COPY_FILES += \
	vendor/samsung/hltedcm/proprietary/lib/libsensirion_h_11.so:system/lib/libsensirion_h_11.so \
	vendor/samsung/hltedcm/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
	vendor/samsung/hltedcm/proprietary/lib/libril.so:system/lib/libril.so \
	vendor/samsung/hltedcm/proprietary/lib/hw/nfc.MSM8974.so:system/lib/hw/nfc.MSM8974.so \
	vendor/samsung/hltedcm/proprietary/lib/hw/sensors.msm8974.so:system/lib/hw/sensors.msm8974.so

PRODUCT_COPY_FILES += \
    vendor/samsung/hltedcm/proprietary/lib/libemojibitmap_type2.so:system/lib/libemojibitmap_type2.so \
    vendor/samsung/hltedcm/proprietary/lib/libemojidata_type2_docomo.so:system/lib/libemojidata_type2_docomo.so \
    vendor/samsung/hltedcm/proprietary/lib/libemoji_docomo.so:system/lib/libemoji_docomo.so \
    vendor/samsung/hltedcm/proprietary/fonts/truetypeEmoji.ttf:system/fonts/truetypeEmoji.ttf \
	vendor/samsung/hltedcm/proprietary/app/FeliCaLock.apk:system/app/FeliCaLock.apk \
	vendor/samsung/hltedcm/proprietary/app/FeliCaRemoteLock.apk:system/app/FeliCaRemoteLock.apk \
	vendor/samsung/hltedcm/proprietary/app/FeliCaTest.apk:system/app/FeliCaTest.apk \
	vendor/samsung/hltedcm/proprietary/app/MobileFeliCaClient.apk:system/app/MobileFeliCaClient.apk \
	vendor/samsung/hltedcm/proprietary/app/MobileFeliCaMenuApp.apk:system/app/MobileFeliCaMenuApp.apk \
	vendor/samsung/hltedcm/proprietary/app/MobileFeliCaSettingApp.apk:system/app/MobileFeliCaSettingApp.apk \
	vendor/samsung/hltedcm/proprietary/app/MobileFeliCaWebPluginBoot.apk:system/app/MobileFeliCaWebPluginBoot.apk \
	vendor/samsung/hltedcm/proprietary/app/FdtpApplication.apk:system/app/FdtpApplication.apk \
	vendor/samsung/hltedcm/proprietary/app/FdtpMfcAccess.apk:system/app/FdtpMfcAccess.apk \
	vendor/samsung/hltedcm/proprietary/bin/mfdp:system/bin/mfdp \
	vendor/samsung/hltedcm/proprietary/bin/mfsc:system/bin/mfsc \
	vendor/samsung/hltedcm/proprietary/lib/libcordon.so:system/lib/libcordon.so \
	vendor/samsung/hltedcm/proprietary/etc/felica/No_ticket.png:system/etc/felica/No_ticket.png \
	vendor/samsung/hltedcm/proprietary/etc/felica/air.png:system/etc/felica/air.png \
	vendor/samsung/hltedcm/proprietary/etc/felica/bookmark.cfg:system/etc/felica/bookmark.cfg \
	vendor/samsung/hltedcm/proprietary/etc/felica/common.cfg:system/etc/felica/common.cfg \
	vendor/samsung/hltedcm/proprietary/etc/felica/id.png:system/etc/felica/id.png \
	vendor/samsung/hltedcm/proprietary/etc/felica/mfc_falp.cfg:system/etc/felica/mfc_falp.cfg \
	vendor/samsung/hltedcm/proprietary/etc/felica/mfc_push.cfg:system/etc/felica/mfc_push.cfg \
	vendor/samsung/hltedcm/proprietary/etc/felica/mfm.cfg:system/etc/felica/mfm.cfg \
	vendor/samsung/hltedcm/proprietary/etc/felica/mfs.cfg:system/etc/felica/mfs.cfg \
	vendor/samsung/hltedcm/proprietary/etc/felica/money.png:system/etc/felica/money.png \
	vendor/samsung/hltedcm/proprietary/etc/felica/portal_icon.png:system/etc/felica/portal_icon.png \
	vendor/samsung/hltedcm/proprietary/etc/felica/toku.png:system/etc/felica/toku.png \
	vendor/samsung/hltedcm/proprietary/etc/felica/train.png:system/etc/felica/train.png \
    vendor/samsung/hltedcm/proprietary/app/SPModePushNotifier.apk:system/app/SPModePushNotifier.apk 
