# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/hltedcm/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/hltedcm/proprietary/etc/Bluetooth_cal.acdb:system/etc/Bluetooth_cal.acdb \
    vendor/samsung/hltedcm/proprietary/etc/Global_cal.acdb:system/etc/Global_cal.acdb \
    vendor/samsung/hltedcm/proprietary/etc/Handset_cal.acdb:system/etc/Handset_cal.acdb \
    vendor/samsung/hltedcm/proprietary/etc/Hdmi_cal.acdb:system/etc/Hdmi_cal.acdb \
    vendor/samsung/hltedcm/proprietary/etc/Headset_cal.acdb:system/etc/Headset_cal.acdb \
    vendor/samsung/hltedcm/proprietary/etc/Speaker_cal.acdb:system/etc/Speaker_cal.acdb \
    vendor/samsung/hltedcm/proprietary/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
    vendor/samsung/hltedcm/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/hltedcm/proprietary/bin/efsks:system/bin/efsks \
    vendor/samsung/hltedcm/proprietary/bin/qcks:system/bin/qcks \
    vendor/samsung/hltedcm/proprietary/lib/hw/sensors.msm8974.so:system/lib/hw/sensors.msm8974.so \
    vendor/samsung/hltedcm/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/hltedcm/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/hltedcm/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/hltedcm/proprietary/lib/libsensirion_h_11.so:system/lib/libsensirion_h_11.so \
    vendor/samsung/hlte-common/proprietary/vendor/firmware/bcm4335_V0105.0486.hcd:system/vendor/firmware/bcm4335_V0105.0486.hcd
