# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/d2dcm/setup-makefiles.sh

# ril
PRODUCT_COPY_FILES += \
	vendor/samsung/d2dcm/proprietary/bin/netmgrd:system/bin/netmgrd \
	vendor/samsung/d2dcm/proprietary/bin/qmiproxy:system/bin/qmiproxy \
	vendor/samsung/d2dcm/proprietary/bin/qmuxd:system/bin/qmuxd \
	vendor/samsung/d2dcm/proprietary/bin/rild:system/bin/rild \
	vendor/samsung/d2dcm/proprietary/bin/rmt_storage:system/bin/rmt_storage \
	vendor/samsung/d2dcm/proprietary/bin/sec-ril:system/bin/sec-ril \
	vendor/samsung/d2dcm/proprietary/lib/libatparser.so:system/lib/libatparser.so \
	vendor/samsung/d2dcm/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
	vendor/samsung/d2dcm/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
	vendor/samsung/d2dcm/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
	vendor/samsung/d2dcm/proprietary/lib/libril.so:system/lib/libril.so \
	vendor/samsung/d2dcm/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
	vendor/samsung/d2dcm/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
	vendor/samsung/d2dcm/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
	vendor/samsung/d2dcm/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
	vendor/samsung/d2dcm/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
	vendor/samsung/d2dcm/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
	vendor/samsung/d2dcm/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
	vendor/samsung/d2dcm/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
	vendor/samsung/d2dcm/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
	vendor/samsung/d2dcm/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
	vendor/samsung/d2dcm/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
	vendor/samsung/d2dcm/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
	vendor/samsung/d2dcm/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
	vendor/samsung/d2dcm/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so

# gps
PRODUCT_COPY_FILES += \
	vendor/samsung/d2dcm/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
	vendor/samsung/d2dcm/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so

# dcm proprietary
PRODUCT_COPY_FILES += \
	vendor/samsung/d2dcm/proprietary/app/FeliCaLock.apk:system/app/FeliCaLock.apk \
	vendor/samsung/d2dcm/proprietary/app/FeliCaRemoteLock.apk:system/app/FeliCaRemoteLock.apk \
	vendor/samsung/d2dcm/proprietary/app/FeliCaTest.apk:system/app/FeliCaTest.apk \
	vendor/samsung/d2dcm/proprietary/app/MobileFeliCaClient.apk:system/app/MobileFeliCaClient.apk \
	vendor/samsung/d2dcm/proprietary/app/MobileFeliCaMenuApp.apk:system/app/MobileFeliCaMenuApp.apk \
	vendor/samsung/d2dcm/proprietary/app/MobileFeliCaSettingApp.apk:system/app/MobileFeliCaSettingApp.apk \
	vendor/samsung/d2dcm/proprietary/app/MobileFeliCaWebPluginBoot.apk:system/app/MobileFeliCaWebPluginBoot.apk \
	vendor/samsung/d2dcm/proprietary/app/SPModePushNotifier.apk:system/app/SPModePushNotifier.apk \
	vendor/samsung/d2dcm/proprietary/bin/mfdp:system/bin/mfdp \
	vendor/samsung/d2dcm/proprietary/bin/mfsc:system/bin/mfsc \
	vendor/samsung/d2dcm/proprietary/etc/felica/No_ticket.png:system/etc/felica/No_ticket.png \
	vendor/samsung/d2dcm/proprietary/etc/felica/air.png:system/etc/felica/air.png \
	vendor/samsung/d2dcm/proprietary/etc/felica/bookmark.cfg:system/etc/felica/bookmark.cfg \
	vendor/samsung/d2dcm/proprietary/etc/felica/common.cfg:system/etc/felica/common.cfg \
	vendor/samsung/d2dcm/proprietary/etc/felica/id.png:system/etc/felica/id.png \
	vendor/samsung/d2dcm/proprietary/etc/felica/mfc_falp.cfg:system/etc/felica/mfc_falp.cfg \
	vendor/samsung/d2dcm/proprietary/etc/felica/mfc_push.cfg:system/etc/felica/mfc_push.cfg \
	vendor/samsung/d2dcm/proprietary/etc/felica/mfm.cfg:system/etc/felica/mfm.cfg \
	vendor/samsung/d2dcm/proprietary/etc/felica/mfs.cfg:system/etc/felica/mfs.cfg \
	vendor/samsung/d2dcm/proprietary/etc/felica/money.png:system/etc/felica/money.png \
	vendor/samsung/d2dcm/proprietary/etc/felica/portal_icon.png:system/etc/felica/portal_icon.png \
	vendor/samsung/d2dcm/proprietary/etc/felica/toku.png:system/etc/felica/toku.png \
	vendor/samsung/d2dcm/proprietary/etc/felica/train.png:system/etc/felica/train.png \
	vendor/samsung/d2dcm/proprietary/fonts/truetypeEmoji.ttf:system/fonts/truetypeEmoji.ttf \
	vendor/samsung/d2dcm/proprietary/lib/libemoji_docomo.so:system/lib/libemoji_docomo.so
