# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/d2lte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/d2lte/proprietary/vendor/firmware/bcm4334.hcd:system/vendor/firmware/bcm4334.hcd \
    vendor/samsung/d2lte/proprietary/vendor/firmware/bcm4334_murata.hcd:system/vendor/firmware/bcm4334_murata.hcd \
    vendor/samsung/d2lte/proprietary/vendor/firmware/bcm4334_semco.hcd:system/vendor/firmware/bcm4334_semco.hcd \
    vendor/samsung/d2lte/proprietary/lib/hw/camera.vendor.msm8960.so:system/lib/hw/camera.vendor.msm8960.so \
    vendor/samsung/d2lte/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/samsung/d2lte/proprietary/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
    vendor/samsung/d2lte/proprietary/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
    vendor/samsung/d2lte/proprietary/lib/libchromatix_ov2720_default_video.so:system/lib/libchromatix_ov2720_default_video.so \
    vendor/samsung/d2lte/proprietary/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
    vendor/samsung/d2lte/proprietary/lib/libchromatix_s5k6a3yx_default_video.so:system/lib/libchromatix_s5k6a3yx_default_video.so \
    vendor/samsung/d2lte/proprietary/lib/libchromatix_s5k6a3yx_preview.so:system/lib/libchromatix_s5k6a3yx_preview.so \
    vendor/samsung/d2lte/proprietary/lib/libchromatix_s5k6a3yx_smart_stay.so:system/lib/libchromatix_s5k6a3yx_smart_stay.so \
    vendor/samsung/d2lte/proprietary/lib/libchromatix_s5k6a3yx_vt_hd.so:system/lib/libchromatix_s5k6a3yx_vt_hd.so \
    vendor/samsung/d2lte/proprietary/lib/libchromatix_s5k6a3yx_vt.so:system/lib/libchromatix_s5k6a3yx_vt.so \
    vendor/samsung/d2lte/proprietary/bin/sec-ril:system/bin/sec-ril \
    vendor/samsung/d2lte/proprietary/blobs/gsm/lib/libril-qc-qmi-1.so:system/blobs/gsm/lib/libril-qc-qmi-1.so \
    vendor/samsung/d2lte/proprietary/blobs/gsm/lib/libril.so:system/blobs/gsm/lib/libril.so \
    vendor/samsung/d2lte/proprietary/blobs/r530/lib/libril-qc-qmi-1.so:system/blobs/r530/lib/libril-qc-qmi-1.so \
    vendor/samsung/d2lte/proprietary/blobs/r530/lib/libril.so:system/blobs/r530/lib/libril.so \
    vendor/samsung/d2lte/proprietary/blobs/spr/lib/libril-qc-qmi-1.so:system/blobs/spr/lib/libril-qc-qmi-1.so \
    vendor/samsung/d2lte/proprietary/blobs/spr/lib/libril.so:system/blobs/spr/lib/libril.so \
    vendor/samsung/d2lte/proprietary/blobs/vzw/lib/libril-qc-qmi-1.so:system/blobs/vzw/lib/libril-qc-qmi-1.so \
    vendor/samsung/d2lte/proprietary/blobs/vzw/lib/libril.so:system/blobs/vzw/lib/libril.so \
    vendor/samsung/d2lte/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
    vendor/samsung/d2lte/proprietary/etc/wifi/bcmdhd_apsta.bin_b2:system/etc/wifi/bcmdhd_apsta.bin_b2 \
    vendor/samsung/d2lte/proprietary/etc/wifi/bcmdhd_p2p.bin_b2:system/etc/wifi/bcmdhd_p2p.bin_b2 \
    vendor/samsung/d2lte/proprietary/etc/wifi/bcmdhd_sta.bin_b2:system/etc/wifi/bcmdhd_sta.bin_b2 \
    vendor/samsung/d2lte/proprietary/etc/wifi/bcmdhd_mfg.bin_b2:system/etc/wifi/bcmdhd_mfg.bin_b2 \
    vendor/samsung/d2lte/proprietary/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
    vendor/samsung/d2lte/proprietary/etc/wifi/nvram_mfg.txt_murata:system/etc/wifi/nvram_mfg.txt_murata \
    vendor/samsung/d2lte/proprietary/etc/wifi/nvram_mfg.txt_murata_b2:system/etc/wifi/nvram_mfg.txt_murata_b2 \
    vendor/samsung/d2lte/proprietary/etc/wifi/nvram_mfg.txt_semcosh:system/etc/wifi/nvram_mfg.txt_semcosh \
    vendor/samsung/d2lte/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/d2lte/proprietary/etc/wifi/nvram_net.txt_murata:system/etc/wifi/nvram_net.txt_murata \
    vendor/samsung/d2lte/proprietary/etc/wifi/nvram_net.txt_murata_b2:system/etc/wifi/nvram_net.txt_murata_b2 \
    vendor/samsung/d2lte/proprietary/etc/wifi/nvram_net.txt_semcosh:system/etc/wifi/nvram_net.txt_semcosh

#for d2dcm
PRODUCT_COPY_FILES += \
        vendor/samsung/d2lte/proprietary/app/FeliCaLock.apk:system/app/FeliCaLock.apk \
        vendor/samsung/d2lte/proprietary/app/FeliCaRemoteLock.apk:system/app/FeliCaRemoteLock.apk \
        vendor/samsung/d2lte/proprietary/app/FeliCaTest.apk:system/app/FeliCaTest.apk \
        vendor/samsung/d2lte/proprietary/app/MobileFeliCaClient.apk:system/app/MobileFeliCaClient.apk \
        vendor/samsung/d2lte/proprietary/app/MobileFeliCaMenuApp.apk:system/app/MobileFeliCaMenuApp.apk \
        vendor/samsung/d2lte/proprietary/app/MobileFeliCaSettingApp.apk:system/app/MobileFeliCaSettingApp.apk \
        vendor/samsung/d2lte/proprietary/app/MobileFeliCaWebPluginBoot.apk:system/app/MobileFeliCaWebPluginBoot.apk \
        vendor/samsung/d2lte/proprietary/app/SPModePushNotifier.apk:system/app/SPModePushNotifier.apk \
        vendor/samsung/d2lte/proprietary/bin/mfdp:system/bin/mfdp \
        vendor/samsung/d2lte/proprietary/bin/mfsc:system/bin/mfsc \
        vendor/samsung/d2lte/proprietary/etc/felica/No_ticket.png:system/etc/felica/No_ticket.png \
        vendor/samsung/d2lte/proprietary/etc/felica/air.png:system/etc/felica/air.png \
        vendor/samsung/d2lte/proprietary/etc/felica/bookmark.cfg:system/etc/felica/bookmark.cfg \
        vendor/samsung/d2lte/proprietary/etc/felica/common.cfg:system/etc/felica/common.cfg \
        vendor/samsung/d2lte/proprietary/etc/felica/id.png:system/etc/felica/id.png \
        vendor/samsung/d2lte/proprietary/etc/felica/mfc_falp.cfg:system/etc/felica/mfc_falp.cfg \
        vendor/samsung/d2lte/proprietary/etc/felica/mfc_push.cfg:system/etc/felica/mfc_push.cfg \
        vendor/samsung/d2lte/proprietary/etc/felica/mfm.cfg:system/etc/felica/mfm.cfg \
        vendor/samsung/d2lte/proprietary/etc/felica/mfs.cfg:system/etc/felica/mfs.cfg \
        vendor/samsung/d2lte/proprietary/etc/felica/money.png:system/etc/felica/money.png \
        vendor/samsung/d2lte/proprietary/etc/felica/portal_icon.png:system/etc/felica/portal_icon.png \
        vendor/samsung/d2lte/proprietary/etc/felica/toku.png:system/etc/felica/toku.png \
        vendor/samsung/d2lte/proprietary/etc/felica/train.png:system/etc/felica/train.png \
        vendor/samsung/d2lte/proprietary/fonts/truetypeEmoji.ttf:system/fonts/truetypeEmoji.ttf \
        vendor/samsung/d2lte/proprietary/lib/libcordon.so:system/lib/libcordon.so \
        vendor/samsung/d2lte/proprietary/lib/libemoji_docomo.so:system/lib/libemoji_docomo.so
