# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/jfltedcm/setup-makefiles.sh

PRODUCT_COPY_FILES += \
        vendor/samsung/jfltedcm/proprietary/lib/libemoji_docomo.so:system/lib/libemoji_docomo.so \
        vendor/samsung/jfltedcm/proprietary/fonts/truetypeEmoji.ttf:system/fonts/truetypeEmoji.ttf \
        vendor/samsung/jfltedcm/proprietary/app/SPModePushNotifier.apk:system/app/SPModePushNotifier.apk \
        vendor/samsung/jfltedcm/proprietary/etc/apns-conf.xml:system/etc/apns-conf.xml \
        vendor/samsung/jfltedcm/proprietary/lib/libril-qc-qmi-1:system/lib/libril-qc-qmi-1 \
        vendor/samsung/jfltedcm/proprietary/lib/libril.so:system/lib/libril.so
